In [45]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/blastchar/telco-customer-churn/WA_Fn-UseC_-Telco-Customer-Churn.csv

In [46]:
import pandas as pd 
import numpy as np
df=pd.read_csv("/kaggle/input/datasets/blastchar/telco-customer-churn/WA_Fn-UseC_-Telco-Customer-Churn.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [48]:
df.nunique()

customerID          7043
gender                 2
SeniorCitizen          2
Partner                2
Dependents             2
tenure                73
PhoneService           2
MultipleLines          3
InternetService        3
OnlineSecurity         3
OnlineBackup           3
DeviceProtection       3
TechSupport            3
StreamingTV            3
StreamingMovies        3
Contract               3
PaperlessBilling       2
PaymentMethod          4
MonthlyCharges      1585
TotalCharges        6531
Churn                  2
dtype: int64

In [49]:
df=df.drop(columns=['customerID'], axis=1)

In [50]:
df["TotalCharges"]=df["TotalCharges"].replace(" ",0)
df["TotalCharges"]=df["TotalCharges"].astype(float)

In [51]:
obj_cols = df.select_dtypes(include=['object']).columns.tolist()
num_cols = df.select_dtypes(include=['number']).columns.tolist()
print(obj_cols)
print(num_cols)

['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'Churn']
['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges']

In [52]:
df=pd.get_dummies(data=df, columns=obj_cols, drop_first=True)

In [53]:
df

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Churn_Yes
0,0,1,29.85,29.85,False,True,False,False,True,False,...,False,False,False,False,False,True,False,True,False,False
1,0,34,56.95,1889.50,True,False,False,True,False,False,...,False,False,False,True,False,False,False,False,True,False
2,0,2,53.85,108.15,True,False,False,True,False,False,...,False,False,False,False,False,True,False,False,True,True
3,0,45,42.30,1840.75,True,False,False,False,True,False,...,False,False,False,True,False,False,False,False,False,False
4,0,2,70.70,151.65,False,False,False,True,False,False,...,False,False,False,False,False,True,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,24,84.80,1990.50,True,True,True,True,False,True,...,True,False,True,True,False,True,False,False,True,False
7039,0,72,103.20,7362.90,False,True,True,True,False,True,...,True,False,True,True,False,True,True,False,False,False
7040,0,11,29.60,346.45,False,True,True,False,True,False,...,False,False,False,False,False,True,False,True,False,False
7041,1,4,74.40,306.60,True,True,False,True,False,True,...,False,False,False,False,False,True,False,False,True,True
7042,0,66,105.65,6844.50,True,False,False,True,False,False,...,True,False,True,False,True,True,False,False,False,False

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 31 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   SeniorCitizen                          7043 non-null   int64
 1   tenure                                 7043 non-null   int64
 2   MonthlyCharges                         7043 non-null   float64
 3   TotalCharges                           7043 non-null   float64
 4   gender_Male                            7043 non-null   bool
 5   Partner_Yes                            7043 non-null   bool
 6   Dependents_Yes                         7043 non-null   bool
 7   PhoneService_Yes                       7043 non-null   bool
 8   MultipleLines_No phone service         7043 non-null   bool
 9   MultipleLines_Yes                      7043 non-null   bool
 10  InternetService_Fiber optic            7043 non-null   bool
 11  InternetService_No                     7043 non-null   bool
 12  OnlineSecurity_No internet service     7043 non-null   bool
 13  OnlineSecurity_Yes                     7043 non-null   bool
 14  OnlineBackup_No internet service       7043 non-null   bool
 15  OnlineBackup_Yes                       7043 non-null   bool
 16  DeviceProtection_No internet service   7043 non-null   bool
 17  DeviceProtection_Yes                   7043 non-null   bool
 18  TechSupport_No internet service        7043 non-null   bool
 19  TechSupport_Yes                        7043 non-null   bool
 20  StreamingTV_No internet service        7043 non-null   bool
 21  StreamingTV_Yes                        7043 non-null   bool
 22  StreamingMovies_No internet service    7043 non-null   bool
 23  StreamingMovies_Yes                    7043 non-null   bool
 24  Contract_One year                      7043 non-null   bool
 25  Contract_Two year                      7043 non-null   bool
 26  PaperlessBilling_Yes                   7043 non-null   bool
 27  PaymentMethod_Credit card (automatic)  7043 non-null   bool
 28  PaymentMethod_Electronic check         7043 non-null   bool
 29  PaymentMethod_Mailed check             7043 non-null   bool
 30  Churn_Yes                              7043 non-null   bool
dtypes: bool(27), float64(2), int64(2)
memory usage: 405.9 KB

In [55]:
df[df.select_dtypes(include=['bool']).columns] = df[df.select_dtypes(include=['bool']).columns].astype(int)

# Converting Boolean Values to Int

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 31 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   SeniorCitizen                          7043 non-null   int64
 1   tenure                                 7043 non-null   int64
 2   MonthlyCharges                         7043 non-null   float64
 3   TotalCharges                           7043 non-null   float64
 4   gender_Male                            7043 non-null   int64
 5   Partner_Yes                            7043 non-null   int64
 6   Dependents_Yes                         7043 non-null   int64
 7   PhoneService_Yes                       7043 non-null   int64
 8   MultipleLines_No phone service         7043 non-null   int64
 9   MultipleLines_Yes                      7043 non-null   int64
 10  InternetService_Fiber optic            7043 non-null   int64
 11  InternetService_No                     7043 non-null   int64
 12  OnlineSecurity_No internet service     7043 non-null   int64
 13  OnlineSecurity_Yes                     7043 non-null   int64
 14  OnlineBackup_No internet service       7043 non-null   int64
 15  OnlineBackup_Yes                       7043 non-null   int64
 16  DeviceProtection_No internet service   7043 non-null   int64
 17  DeviceProtection_Yes                   7043 non-null   int64
 18  TechSupport_No internet service        7043 non-null   int64
 19  TechSupport_Yes                        7043 non-null   int64
 20  StreamingTV_No internet service        7043 non-null   int64
 21  StreamingTV_Yes                        7043 non-null   int64
 22  StreamingMovies_No internet service    7043 non-null   int64
 23  StreamingMovies_Yes                    7043 non-null   int64
 24  Contract_One year                      7043 non-null   int64
 25  Contract_Two year                      7043 non-null   int64
 26  PaperlessBilling_Yes                   7043 non-null   int64
 27  PaymentMethod_Credit card (automatic)  7043 non-null   int64
 28  PaymentMethod_Electronic check         7043 non-null   int64
 29  PaymentMethod_Mailed check             7043 non-null   int64
 30  Churn_Yes                              7043 non-null   int64
dtypes: float64(2), int64(29)
memory usage: 1.7 MB

# Model Training

In [60]:
X=df.drop("Churn_Yes", axis=1)
y=df["Churn_Yes"]

In [61]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [63]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

In [64]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from xgboost import XGBClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    classification_report,
    confusion_matrix
)

In [65]:
xgb = XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric='logloss'
)

xgb.fit(X_train, y_train)

y_pred_xgb = xgb.predict(X_test)

print("Accuracy:",
      accuracy_score(y_test, y_pred_xgb)*100)

print("ROC-AUC:",
      roc_auc_score(y_test,
                    xgb.predict_proba(X_test)[:,1])*100)

Accuracy: 79.55997161107167
ROC-AUC: 83.35412953060013

In [66]:
rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42
)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

In [67]:
print("Accuracy:",
      accuracy_score(y_test, y_pred_rf)*100)

print("ROC-AUC:",
      roc_auc_score(y_test,
                    rf.predict_proba(X_test)[:,1])*100)

Accuracy: 79.4180269694819
ROC-AUC: 82.72417267302177